# Generated by Django 3.2 on 2023-03-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# yapf: disable

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passes/')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

# yapf: enable
