# Generated by Django 3.2 on 2023-03-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfuid', models.CharField(max_length=20)),
                ('valid_from', models.DateTimeField(verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pass_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='passes.passholder')),
            ],
        ),
    ]
